const fs = require('fs')
const configData = JSON.parse(fs.readFileSync('config.json', 'utf-8'))
const phones = configData['phones']
const filename = `${__dirname}/${configData['grammarFile']}`

fs.writeFileSync(filename, '<?xml version="1.0" encoding="UTF-8"?> \n\n')
fs.writeFileSync(filename, '<grammar xml:lang="en-US" tag-format="semantics-ms/1.0" version="1.0" root="PersyColor" mode="voice" xmlns="http://www.w3.org/2001/06/grammar"> \n', {flag: 'a'})
fs.writeFileSync(filename, '<rule id="PersyColor" scope="public"> \n', {flag: 'a'})
fs.writeFileSync(filename, '        <item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item repeat="0-1"><ruleref uri="#UMFILLER"/></item> \n', {flag: 'a'})
fs.writeFileSync(filename, '                <item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                    <one-of>\n', {flag: 'a'})
phones.forEach(phone => {
    fs.writeFileSync(filename, `                        <item>${phone["location"].toLowerCase()}<tag>$._value = \"${phone['location']}\";</tag></item>\n`, {flag: 'a'})
});
fs.writeFileSync(filename, '                    </one-of>\n', {flag: 'a'})
fs.writeFileSync(filename, '                </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item repeat="0-1"><ruleref uri="#TRAILERS"/></item> \n', {flag: 'a'})
fs.writeFileSync(filename, '        </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '</rule>\n\n', {flag: 'a'})
fs.writeFileSync(filename, '<rule id="UMFILLER">\n', {flag: 'a'})
fs.writeFileSync(filename, '        <one-of>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> uh </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> um </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> hm </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> ah </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> er </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '        </one-of>\n', {flag: 'a'})
fs.writeFileSync(filename, '</rule>\n\n', {flag: 'a'})
fs.writeFileSync(filename, '<rule id="TRAILERS">\n', {flag: 'a'})
fs.writeFileSync(filename, '        <one-of>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> maam </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '                <item> sir </item>\n', {flag: 'a'})
fs.writeFileSync(filename, '        </one-of>\n', {flag: 'a'})
fs.writeFileSync(filename, '</rule>\n\n', {flag: 'a'})
fs.writeFileSync(filename, '</grammar>', {flag: 'a'})
